### ISSUE TITLE
Hang when parsing svg tag

### ISSUE THREAD

**Issue by mganss** [jamietre/CsQuery#194]
The following causes a hang:

```HTML
var dom = CQ.Create("<svg x=y/>");
```

This does not:

```HTML
var dom = CQ.Create("<svg x=y />"); // space after y
```

This neither:

```HTML
var dom = CQ.Create("<div x=y/>");
```

**Comment by mganss** [comment]
Could you make a new NuGet release?

**Comment by 304NotModified** [comment]
Really bad that you don't get even a response.

**Comment by jamietre** [comment]
Sorry - but the reality I haven't used CsQuery in my work for over two years. I hardly even work in .NET at all. So I have very little time or incentive to put much effort into it.

The problem with making a new release is that there are a a number of changes merged from pull requests that I haven't had much time to look at. If release the code as it is today, I might cause more problems then I solve. I know that the current release is pretty stable, and the only significant issue that I know of isn't fixed today.

I would gladly make anyone who is using CsQuery on a regular basis and wants to be take the reins a collaborator. I just don't want to be the guy to publish a new release and then feel responsible for a hundred issues if something goes wrong.

**Comment by 304NotModified** [comment]
Thanks for the response!
