### ISSUE TITLE
ChildMatches returns null for :first-child selector

### ISSUE THREAD

**Issue by coel** [jamietre/CsQuery#208]
I seem to get a `NullReferenceException` on a document using and matching the `:first-child` selector.

Debugging into it, it seems like the cause is `ChildMatches()` in FirstChild.cs returning `null`.

        public override IEnumerable<IDomObject> ChildMatches(IDomContainer element)
        {
            IDomObject child = element.FirstChild;
            if (child != null)
            {
                yield return element.FirstElementChild;
            }
        }

For example, `null` is returned on a p tag with text where `element.FirstChild` returns the text, but `element.FirstElementChild` is `null`.

Looking at LastChild.cs, it uses `element.LastElementChild` for both the check and to return.

Is the handling for FirstChild intentionally different, or is this likely a bug?

**Comment by jamietre** [comment]
Looks like a bug. IIRC ChildMatches should never return null.
